import { defineCatalog } from "@json-render/core";
import { schema } from "@json-render/react/schema";
import { z } from "zod";

// =============================================================================
// Shared 3D schemas
// =============================================================================

const vec3 = z.array(z.number());

const animation3D = z
  .object({
    rotate: vec3.nullable(),
  })
  .nullable();

const transform3DProps = {
  position: vec3.nullable(),
  rotation: vec3.nullable(),
  scale: vec3.nullable(),
};

const material3DProps = {
  color: z.string().nullable(),
  metalness: z.number().nullable(),
  roughness: z.number().nullable(),
  emissive: z.string().nullable(),
  emissiveIntensity: z.number().nullable(),
  wireframe: z.boolean().nullable(),
  opacity: z.number().nullable(),
};

const mesh3DProps = {
  ...transform3DProps,
  ...material3DProps,
  args: z.array(z.number()).nullable(),
  animation: animation3D,
};

/**
 * json-render + AI SDK Example Catalog
 *
 * Components for rendering data dashboards generated by the ToolLoopAgent.
 * Data flows in through tools (weather, GitHub, crypto, HN), not user actions.
 */
export const explorerCatalog = defineCatalog(schema, {
  components: {
    // Layout
    Stack: {
      props: z.object({
        direction: z.enum(["horizontal", "vertical"]).nullable(),
        gap: z.enum(["sm", "md", "lg"]).nullable(),
        align: z.enum(["start", "center", "end", "stretch"]).nullable(),
        justify: z
          .enum(["start", "center", "end", "between", "around"])
          .nullable(),
        className: z.string().nullable(),
      }),
      slots: ["default"],
      description: "Flex container for layouts",
      example: { direction: "vertical", gap: "md", align: null, justify: null },
    },

    Card: {
      props: z.object({
        title: z.string().nullable(),
        description: z.string().nullable(),
        maxWidth: z.enum(["xs", "sm", "md", "lg", "xl", "full"]).nullable(),
        centered: z.boolean().nullable(),
      }),
      slots: ["default"],
      description:
        "Card container that wraps child elements (Stack, Metric, Separator, etc.) with visual grouping. Use as children of Grid for comparison layouts. ALWAYS define Card elements you reference — if Grid has children: ['a-card'], then 'a-card' MUST exist as a Card element with its own children array. maxWidth: xs=320px, sm=384px, md=448px, lg=512px, xl=576px, full=100%. centered: true horizontally centers via mx-auto.",
      example: {
        title: "Login",
        description: "Sign in to your account",
        maxWidth: "sm",
        centered: true,
      },
    },

    Grid: {
      props: z.object({
        columns: z.enum(["1", "2", "3", "4"]).nullable(),
        gap: z.enum(["sm", "md", "lg"]).nullable(),
      }),
      slots: ["default"],
      description: "Responsive grid layout container",
      example: { columns: "3", gap: "md" },
    },

    // Typography
    Heading: {
      props: z.object({
        text: z.string(),
        level: z.enum(["h1", "h2", "h3", "h4"]).nullable(),
      }),
      description: "Section heading",
      example: { text: "Data Explorer", level: "h1" },
    },

    Text: {
      props: z.object({
        content: z.string(),
        muted: z.boolean().nullable(),
      }),
      description: "Text content",
      example: { content: "Here is your data overview." },
    },

    // Data display
    Badge: {
      props: z.object({
        text: z.string(),
        variant: z
          .enum(["default", "secondary", "destructive", "outline"])
          .nullable(),
      }),
      description: "Status badge",
      example: { text: "Live", variant: "default" },
    },

    Alert: {
      props: z.object({
        variant: z.enum(["default", "destructive"]).nullable(),
        title: z.string(),
        description: z.string().nullable(),
      }),
      description: "Alert or info message",
    },

    Separator: {
      props: z.object({
        orientation: z.enum(["horizontal", "vertical"]).nullable(),
      }),
      description: "Visual separator line",
      example: { orientation: null },
    },

    Metric: {
      props: z.object({
        label: z.string(),
        value: z.string(),
        detail: z.string().nullable(),
        trend: z.enum(["up", "down", "neutral"]).nullable(),
      }),
      description:
        "Single metric display with label, value, and optional trend indicator",
      example: {
        label: "Temperature",
        value: "72F",
        detail: "Feels like 68F",
        trend: "up",
      },
    },

    Table: {
      props: z.object({
        data: z.array(z.record(z.string(), z.unknown())),
        columns: z.array(
          z.object({
            key: z.string(),
            label: z.string(),
          }),
        ),
        emptyMessage: z.string().nullable(),
      }),
      description:
        'Data table. Use { "$state": "/path" } to bind read-only data from state.',
      example: {
        data: { $state: "/stories" },
        columns: [
          { key: "title", label: "Title" },
          { key: "score", label: "Score" },
        ],
      },
    },

    Link: {
      props: z.object({
        text: z.string(),
        href: z.string(),
      }),
      description: "External link that opens in a new tab",
      example: { text: "View on GitHub", href: "https://github.com" },
    },

    Avatar: {
      props: z.object({
        src: z.string(),
        alt: z.string(),
        fallback: z.string().nullable(),
        size: z.enum(["sm", "default", "lg"]).nullable(),
      }),
      description:
        "Small rounded icon for favicons, user avatars, logos, and status icons ONLY. Do NOT use Avatar for content images, thumbnails, or article previews — use Image instead. fallback is 1-2 chars shown if image fails to load.",
      example: {
        src: "https://www.accuweather.com/assets/images/weather-icons/v2a/1.svg",
        alt: "Sunny",
        fallback: "☀",
        size: "default",
      },
    },

    Image: {
      props: z.object({
        src: z.string(),
        alt: z.string(),
        width: z.string().nullable(),
        height: z.string().nullable(),
        rounded: z.enum(["none", "sm", "md", "lg", "xl", "full"]).nullable(),
        objectFit: z.enum(["cover", "contain", "fill", "none"]).nullable(),
        align: z.enum(["left", "center", "right"]).nullable(),
      }),
      description:
        "Displays an image from a URL. Use for content images, thumbnails, article previews, and search result images. Set width/height as CSS values (e.g. '100%', '200px'). rounded controls border-radius. objectFit controls how the image fills its container (default: cover). align controls horizontal self-alignment within a flex parent: 'right' pushes the image to the right via margin-left auto (useful inside Cards and vertical Stacks).",
      example: {
        src: "https://example.com/image.jpg",
        alt: "Article preview",
        width: "160px",
        height: "120px",
        rounded: "lg",
        objectFit: "cover",
        align: "right",
      },
    },

    // Charts
    BarChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        xKey: z.string(),
        yKey: z.string(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        'Bar chart visualization. Use { "$state": "/path" } to bind read-only data. xKey is the category field, yKey is the numeric value field.',
    },

    LineChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        xKey: z.string(),
        yKey: z.string(),
        yKeys: z
          .array(
            z.object({
              key: z.string(),
              label: z.string().nullable(),
              color: z.string().nullable(),
            }),
          )
          .nullable(),
        aggregate: z.enum(["sum", "count", "avg"]).nullable(),
        color: z.string().nullable(),
        height: z.number().nullable(),
      }),
      description:
        'Line chart visualization. Use { "$state": "/path" } to bind read-only data. xKey is the x-axis field, yKey is the numeric value field for a single line. For multiple lines, use yKeys: [{key, label, color}] — each entry adds a separate line. When yKeys is provided, yKey is ignored.',
    },

    // Interactive
    Tabs: {
      props: z.object({
        defaultValue: z.string().nullable(),
        value: z.string().nullable(),
        tabs: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      slots: ["default"],
      description:
        'Tabbed content container. Use { "$bindState": "/path" } on value for two-way binding — the active tab value is written to state so other components (Metric, Text, etc.) can use visible conditions to react to tab changes. defaultValue sets the initially selected tab when value is not bound.',
      example: {
        defaultValue: "1d",
        value: { $bindState: "/activeTab" },
        tabs: [
          { value: "1d", label: "1D" },
          { value: "1mo", label: "1M" },
        ],
      },
    },

    TabContent: {
      props: z.object({
        value: z.string(),
      }),
      slots: ["default"],
      description: "Content for a specific tab",
    },

    Progress: {
      props: z.object({
        value: z.number(),
        max: z.number().nullable(),
        label: z.string().nullable(),
      }),
      description: "Progress bar (value 0-100)",
      example: { value: 65, max: null, label: "Upload progress" },
    },

    Skeleton: {
      props: z.object({
        width: z.string().nullable(),
        height: z.string().nullable(),
      }),
      description: "Loading placeholder",
    },

    // Educational / Rich content
    Callout: {
      props: z.object({
        type: z.enum(["info", "tip", "warning", "important"]).nullable(),
        title: z.string().nullable(),
        content: z.string(),
      }),
      description:
        "Highlighted callout box for tips, warnings, notes, or key information",
      example: {
        type: "tip",
        title: "Did you know?",
        content: "The sun is about 93 million miles from Earth.",
      },
    },

    Accordion: {
      props: z.object({
        items: z.array(
          z.object({
            title: z.string(),
            content: z.string(),
          }),
        ),
        type: z.enum(["single", "multiple"]).nullable(),
      }),
      description:
        "Collapsible accordion sections for organizing detailed content",
      example: {
        items: [{ title: "Overview", content: "A brief introduction." }],
        type: "multiple",
      },
    },

    Timeline: {
      props: z.object({
        items: z.array(
          z.object({
            title: z.string(),
            description: z.string().nullable(),
            date: z.string().nullable(),
            status: z.enum(["completed", "current", "upcoming"]).nullable(),
          }),
        ),
      }),
      description:
        "Vertical timeline showing ordered events, steps, or historical milestones",
      example: {
        items: [
          {
            title: "Discovery",
            description: "Initial breakthrough",
            date: "1905",
            status: "completed",
          },
        ],
      },
    },

    PieChart: {
      props: z.object({
        title: z.string().nullable(),
        data: z.array(z.record(z.string(), z.unknown())),
        nameKey: z.string(),
        valueKey: z.string(),
        height: z.number().nullable(),
      }),
      description:
        'Pie/donut chart for proportional data. Use { "$state": "/path" } to bind read-only data. nameKey is the label field, valueKey is the numeric value field.',
    },

    // Interactive / Input
    RadioGroup: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        options: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      description:
        'Radio button group for single selection. Use { "$bindState": "/path" } for two-way binding. Use for multiple-choice questions, settings, or any single-select input.',
      example: {
        label: "Choose one",
        value: { $bindState: "/answer" },
        options: [
          { value: "a", label: "Option A" },
          { value: "b", label: "Option B" },
        ],
      },
    },

    SelectInput: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        placeholder: z.string().nullable(),
        options: z.array(
          z.object({
            value: z.string(),
            label: z.string(),
          }),
        ),
      }),
      description:
        'Dropdown select input. Use { "$bindState": "/path" } for two-way binding. Use when there are many options and a dropdown is more compact than radio buttons.',
      example: {
        label: "Country",
        value: { $bindState: "/selectedCountry" },
        placeholder: "Select a country",
        options: [
          { value: "us", label: "United States" },
          { value: "uk", label: "United Kingdom" },
        ],
      },
    },

    TextInput: {
      props: z.object({
        label: z.string().nullable(),
        value: z.string().nullable(),
        placeholder: z.string().nullable(),
        type: z.enum(["text", "email", "number", "password", "url"]).nullable(),
      }),
      description:
        'Text input field. Use { "$bindState": "/path" } for two-way binding. Use for free-text entry like names, emails, search, etc.',
      example: {
        label: "Your name",
        value: { $bindState: "/userName" },
        placeholder: "Enter your name",
        type: "text",
      },
    },

    Button: {
      props: z.object({
        label: z.string(),
        variant: z
          .enum(["default", "secondary", "destructive", "outline", "ghost"])
          .nullable(),
        size: z.enum(["default", "sm", "lg"]).nullable(),
        disabled: z.boolean().nullable(),
      }),
      description:
        "Clickable button. Use with on.press to trigger actions like setState, pushState, etc. Can be used for quiz submissions, form actions, navigation, and more.",
      example: {
        label: "Submit",
        variant: "default",
        size: "default",
        disabled: null,
      },
    },

    ProjectileSimulator: {
      props: z.object({
        gravity: z.number().nullable(),
        initialVelocity: z.number().nullable(),
        angle: z.number().nullable(),
        height: z.number().nullable(),
      }),
      description:
        'Interactive 2D projectile physics simulation. User can set gravity (m/s²), initial velocity (m/s), launch angle (degrees), and initial height (m). Use { "$bindState": "/path" } for each prop so the inputs are two-way bound. Renders a grid with axes and animates the projectile when the user clicks Launch. Use when the user asks for a projectile simulation, ballistics, or trajectory demo.',
      example: {
        gravity: { $bindState: "/gravity" },
        initialVelocity: { $bindState: "/initialVelocity" },
        angle: { $bindState: "/angle" },
        height: { $bindState: "/height" },
      },
    },

    // =========================================================================
    // Map Components (Mapbox GL)
    // =========================================================================

    Map: {
      props: z.object({
        latitude: z.number(),
        longitude: z.number(),
        zoom: z.number().nullable(),
        mapStyle: z
          .enum([
            "streets",
            "outdoors",
            "light",
            "dark",
            "satellite",
            "satellite-streets",
          ])
          .nullable(),
        markers: z
          .array(
            z.object({
              latitude: z.number(),
              longitude: z.number(),
              label: z.string().nullable(),
              color: z.string().nullable(),
              description: z.string().nullable(),
              address: z.string().nullable(),
              rating: z.number().nullable(),
              image: z.string().nullable(),
              category: z.string().nullable(),
            }),
          )
          .nullable(),
        height: z.string().nullable(),
      }),
      description:
        "Interactive Google Maps-style Mapbox map with a left-side overlay panel showing location cards. IMPORTANT: Before using this component, you MUST call geocodePlaces to get real latitude/longitude for the map center AND every marker. Every marker MUST have its own latitude and longitude — markers without coordinates will not render. markers[] supports: label, description, address, rating (0-5), image URL, category, color. mapStyle: 'streets' for city, 'satellite' for terrain, 'dark' for dashboards.",
      example: {
        latitude: 37.7862,
        longitude: -122.4233,
        zoom: 14,
        mapStyle: "streets",
        markers: [
          {
            latitude: 37.7888,
            longitude: -122.4099,
            label: "House of Prime Rib",
            color: "#EF4444",
            description: "Classic prime rib served tableside in an old-school setting.",
            address: "1906 Van Ness Ave, San Francisco, CA",
            rating: 4.5,
            image: null,
            category: "Restaurant",
          },
          {
            latitude: 37.7835,
            longitude: -122.4367,
            label: "Nopa",
            color: "#EF4444",
            description: "Organic California cuisine in a lively setting.",
            address: "560 Divisadero St, San Francisco, CA",
            rating: 4.4,
            image: null,
            category: "Restaurant",
          },
        ],
        height: null,
      },
    },

    // =========================================================================
    // 3D Scene Components (React Three Fiber)
    // =========================================================================

    // Containers
    Scene3D: {
      props: z.object({
        height: z.string().nullable(),
        background: z.string().nullable(),
        cameraPosition: vec3.nullable(),
        cameraFov: z.number().nullable(),
        autoRotate: z.boolean().nullable(),
      }),
      slots: ["default"],
      description:
        "3D scene container with orbit controls. All 3D components (Sphere, Box, lights, etc.) must be children of a Scene3D. height is a CSS value like '500px'.",
      example: {
        height: "500px",
        background: "#000010",
        cameraPosition: [0, 25, 45],
        cameraFov: null,
        autoRotate: null,
      },
    },

    Group3D: {
      props: z.object({
        ...transform3DProps,
        animation: animation3D,
      }),
      slots: ["default"],
      description:
        "3D group for positioning, rotating, and animating children together. Use to create orbits: position a planet inside a Group3D and animate the group's rotation.",
      example: {
        position: null,
        rotation: null,
        scale: null,
        animation: { rotate: [0, 0.005, 0] },
      },
    },

    HoverableGroup3D: {
      props: z.object({
        ...transform3DProps,
        animation: animation3D,
        label: z.string().nullable(),
        labelPosition: vec3.nullable(),
        labelFontSize: z.number().nullable(),
        labelColor: z.string().nullable(),
      }),
      slots: ["default"],
      description:
        "3D group that shows an optional label only when the user hovers over its children. Use to label planets on hover. Pass label and labelPosition props.",
      example: {
        label: "Mercury",
        labelPosition: [5, 0.6, 0],
        labelFontSize: 0.4,
        labelColor: "#ffffff",
      },
    },

    // Geometry primitives
    Box: {
      props: z.object(mesh3DProps),
      description:
        "3D box/cube mesh. args: [width, height, depth]. Supports on.press for click interaction.",
      example: {
        position: [0, 0, 0],
        color: "#4488ff",
        args: [1, 1, 1],
      },
    },

    Sphere: {
      props: z.object(mesh3DProps),
      description:
        "3D sphere mesh. args: [radius, widthSegments, heightSegments]. Use higher segment counts (32+) for smooth spheres.",
      example: {
        position: [0, 0, 0],
        color: "#4B7BE5",
        args: [1, 32, 32],
      },
    },

    Cylinder: {
      props: z.object(mesh3DProps),
      description:
        "3D cylinder mesh. args: [radiusTop, radiusBottom, height, radialSegments].",
      example: {
        position: [0, 0, 0],
        color: "#88aa44",
        args: [1, 1, 2, 32],
      },
    },

    Cone: {
      props: z.object(mesh3DProps),
      description: "3D cone mesh. args: [radius, height, radialSegments].",
      example: {
        position: [0, 0, 0],
        color: "#ff8844",
        args: [1, 2, 32],
      },
    },

    Torus: {
      props: z.object(mesh3DProps),
      description:
        "3D torus (donut) mesh. args: [radius, tube, radialSegments, tubularSegments].",
      example: {
        position: [0, 0, 0],
        color: "#aa44ff",
        args: [1, 0.4, 16, 100],
      },
    },

    Plane: {
      props: z.object(mesh3DProps),
      description:
        "3D flat plane mesh. args: [width, height]. Useful for ground planes or flat surfaces.",
      example: {
        position: [0, -1, 0],
        rotation: [-Math.PI / 2, 0, 0],
        color: "#334455",
        args: [10, 10],
      },
    },

    Ring: {
      props: z.object(mesh3DProps),
      description:
        "3D flat ring mesh. args: [innerRadius, outerRadius, thetaSegments]. Great for orbit path indicators.",
      example: {
        position: [0, 0, 0],
        rotation: [-Math.PI / 2, 0, 0],
        color: "#ffffff",
        opacity: 0.2,
        args: [14.8, 15.2, 64],
      },
    },

    // Lights
    AmbientLight: {
      props: z.object({
        color: z.string().nullable(),
        intensity: z.number().nullable(),
      }),
      description:
        "Ambient light that illuminates all objects equally. Use for base scene illumination.",
      example: { color: null, intensity: 0.3 },
    },

    PointLight: {
      props: z.object({
        position: vec3.nullable(),
        color: z.string().nullable(),
        intensity: z.number().nullable(),
        distance: z.number().nullable(),
      }),
      description:
        "Point light that emits from a position in all directions. Use for suns, lamps, etc.",
      example: { position: [0, 0, 0], intensity: 2 },
    },

    DirectionalLight: {
      props: z.object({
        position: vec3.nullable(),
        color: z.string().nullable(),
        intensity: z.number().nullable(),
      }),
      description:
        "Directional light like sunlight. Position sets direction, not location.",
      example: { position: [5, 10, 5], intensity: 1 },
    },

    // Helpers (drei)
    Stars: {
      props: z.object({
        radius: z.number().nullable(),
        depth: z.number().nullable(),
        count: z.number().nullable(),
        factor: z.number().nullable(),
        fade: z.boolean().nullable(),
        speed: z.number().nullable(),
      }),
      description:
        "Starfield background for space scenes. Renders thousands of tiny points around the scene.",
      example: { count: 5000, fade: true },
    },

    Label3D: {
      props: z.object({
        text: z.string(),
        position: vec3.nullable(),
        rotation: vec3.nullable(),
        color: z.string().nullable(),
        fontSize: z.number().nullable(),
        anchorX: z.enum(["left", "center", "right"]).nullable(),
        anchorY: z.enum(["top", "middle", "bottom"]).nullable(),
      }),
      description:
        "Text label rendered in 3D space. Always faces the camera (billboard). Use for labeling objects in a scene.",
      example: {
        text: "Earth",
        position: [15, 2, 0],
        color: "#ffffff",
        fontSize: 0.8,
      },
    },

    PlanetInfoOverlay: {
      props: z.object({
        className: z.string().nullable(),
      }),
      description:
        "Overlay that shows planet info from state (set by fetchPlanetInfo action). Place above Scene3D in a Stack. Reads /planetInfo from state.",
      example: { className: null },
    },

    // =========================================================================
    // 2D Scene Components (SVG)
    // =========================================================================

    Scene2D: {
      props: z.object({
        width: z.string().nullable(),
        height: z.string().nullable(),
        viewBox: z.string().nullable(),
        background: z.string().nullable(),
      }),
      slots: ["default"],
      description:
        "2D SVG scene container. All 2D components must be children of Scene2D. width/height are CSS values (e.g. '100%', '500px'). viewBox defines the coordinate system 'min-x min-y width height'.",
      example: {
        width: "100%",
        height: "400px",
        viewBox: "0 0 800 600",
        background: "#f0f0f0",
      },
    },

    Group2D: {
      props: z.object({
        transform: z.string().nullable(),
        x: z.number().nullable(),
        y: z.number().nullable(),
        rotation: z.number().nullable(),
        scale: z.number().nullable(),
      }),
      slots: ["default"],
      description:
        "2D group container for transforming children together. Supports SVG transform string or individual x/y/rotation/scale properties.",
      example: {
        x: 100,
        y: 100,
        rotation: 45,
        scale: 1.5,
      },
    },

    Rect: {
      props: z.object({
        x: z.number(),
        y: z.number(),
        width: z.number(),
        height: z.number(),
        fill: z.string().nullable(),
        stroke: z.string().nullable(),
        strokeWidth: z.number().nullable(),
        rx: z.number().nullable(),
      }),
      description: "2D rectangle. rx is corner radius.",
      example: {
        x: 10,
        y: 10,
        width: 100,
        height: 50,
        fill: "#ff0000",
        rx: 5,
      },
    },

    Circle: {
      props: z.object({
        cx: z.number(),
        cy: z.number(),
        r: z.number(),
        fill: z.string().nullable(),
        stroke: z.string().nullable(),
        strokeWidth: z.number().nullable(),
      }),
      description: "2D circle.",
      example: {
        cx: 50,
        cy: 50,
        r: 25,
        fill: "#00ff00",
      },
    },

    Line: {
      props: z.object({
        x1: z.number(),
        y1: z.number(),
        x2: z.number(),
        y2: z.number(),
        stroke: z.string().nullable(),
        strokeWidth: z.number().nullable(),
        strokeDasharray: z.string().nullable(),
      }),
      description: "2D line segment.",
      example: {
        x1: 0,
        y1: 0,
        x2: 100,
        y2: 100,
        stroke: "#0000ff",
        strokeWidth: 2,
      },
    },

    Path: {
      props: z.object({
        d: z.string(),
        fill: z.string().nullable(),
        stroke: z.string().nullable(),
        strokeWidth: z.number().nullable(),
      }),
      description: "2D path using SVG path data syntax (M, L, C, Z, etc.).",
      example: {
        d: "M 10 10 L 50 10 L 30 50 Z",
        fill: "none",
        stroke: "black",
      },
    },

    Text2D: {
      props: z.object({
        text: z.string(),
        x: z.number(),
        y: z.number(),
        fontSize: z.number().nullable(),
        fill: z.string().nullable(),
        textAnchor: z.enum(["start", "middle", "end"]).nullable(),
        dominantBaseline: z
          .enum(["auto", "middle", "hanging", "central"])
          .nullable(),
        fontWeight: z.union([z.string(), z.number()]).nullable(),
      }),
      description: "2D text label.",
      example: {
        text: "Hello World",
        x: 100,
        y: 100,
        fontSize: 16,
        fill: "#333",
      },
    },
  },

  actions: {
    fetchPlanetInfo: {
      params: z.object({ planet: z.string() }),
      description: "Fetch basic planet facts from API and set /planetInfo in state. Used by solar scene hover.",
    },
  },
});